baseURL = '/'
title = 'Eleva-Jets'
timeZone = "Europe/Paris"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[languages]
  [languages.fr]
    languageName = "Français"
    languageCode = "fr-FR"
    weight = 1

[permalinks]
  pages-legales = "/:slug/"

[imaging]
quality = 80
resampleFilter = "Lanczos"

[markup]
  [markup.goldmark.renderer]
  unsafe = true

  [markup.highlight]
  style = 'monokai'

  [markup.tableOfContents]
  startLevel = 2
  endLevel = 5
  ordered = true

[build]
  [build.buildStats]
    enable = true

[[build.cachebusters]]
  source = "assets/notwatching/hugo_stats\\.json"
  target = "css"
[[build.cachebusters]]
  source = "(postcss|tailwind)\\.config\\.js"
  target = "css"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    disableWatch = true
    source = "hugo_stats.json"
    target = "assets/notwatching/hugo_stats.json"
